# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-cli/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    active: true
style:
  ReturnCount:
    max: 10
  ForbiddenComment:
    allowedPatterns: 'TODO'